
% agent Noa's KB for running in a labyrinth


%%%%%%%%%%%%%%%%%%
%%   ONTOLOGY   %%
%%%%%%%%%%%%%%%%%%

% declare topics

:- kassert(topic(monster)).
:- kassert(topic(wall)).
:- kassert(topic(treasure)).
:- kassert(topic(path)).
:- kassert(topic(fight)).

% semantic links between topics


% relevance of events to topics


%%%%%%%%%%%%%%%%%
%% AGENT STATE %%
%% stamina,    %%
%% carrying,   %%
%% position    %%
%% vision      %%
%%             %%
%% luck        %%
%% agility     %%
%% etc         %%
%%             %%
%%%%%%%%%%%%%%%%%

% beliefs about own state: stamina...
% supposed to be right!

% name of the agent explorer in the labyrinth
% simply assert several values if there are several explorers
:- kassert(explorer(noa)).

% initial position (physical)
:- kassert(position(0,0,noa)).

% belief about own position in NW corner (entrance)
:- kassert(bel(noa,position(0,0,noa),1,0,conviction)). 

% belief about initial stamina
:- kassert(bel(noa,stamina(noa,10),1,0,conviction)).

% beliefs about available weapons
:- kassert(bel(noa,carry(noa,weapon(sword,3,0)),1,0,conviction)). 

% beliefs about physical attributes
% field of vision - belief or fact?
:- kassert(bel(noa,vision(noa,5),1,0,conviction)).
:- kassert(vision(noa,5)).
% strength
:- kassert(bel(noa,strength(noa,7),1,0,conviction)).

% beliefs about the labyrinth: dynamic via exploration
% positions of walls, entrance, exit, enemies (and their strength), 
%              treasures (and their value)

% labyrinth entrance is in x=0,y=0
:- kassert(bel(noa,position(0,0,entrance),1,0,conviction)). 

% position of recharge base to increase stamina
:- kassert(bel(noa,position(0,0,recharge),1,0,conviction)). 


%%%%%%%%%%%%%%%
%% LABYRINTH %%
%%%%%%%%%%%%%%%

% physical description of labyrinth
% to be loaded from a file generated by Java maze maker (Vic)

% generated by java maze class
:- [laby1].

%:- kassert(position(0,0,entrance)).
%:- kassert(position(1,1,wall)).
%:- kassert(position(1,0,path)).
%:- kassert(position(3,2,treasure)).
%:- kassert(position(3,4,enemy)).
%:- kassert(position(6,5,object)).

% enemy(name,strength)
% treasure(name,value)
% object(name,type)
% weapon(type,attack,defense)


%%%%%%%%%%%%%
%%% TOOLS %%%
%%%%%%%%%%%%%

%%%%%%%
%% distance
%%%%%%%

% vertical move
distance(X1,Y1,X1,Y2,D) :- abs(Y2-Y1,D).

% horizontal move
distance(X1,Y1,X2,Y1,D) :- abs(X2-X1,D).

% diagonal move : add vertical and horizontal distance
distance(X1,Y1,X2,Y2,D) :- abs(X2-X1,DX),abs(Y2-Y1,DY),D is DX+DY.


%%%%%%%%
%% field of vision
%%%%%%%%

cansee(Agent,Something) :- 
	% position of agent
	position(XA,YA,Agent),
	% position of something
	position(XS,YS,Something),
	% distance to this thing
	distance(XA,YA,XS,YS,D),
	% field of vision of agent
	vision(Agent,Vision),
	% thing is close enough
	Vision >= D,!.


%%%%%%%%%%%%%%%%%%%%%%%%
%% ENVIRONMENT EVENTS %%
%%%%%%%%%%%%%%%%%%%%%%%%

% what events can occur (event(EventName,Csq)) : something is at a given position
% what topics they are relevant to : monsters, treasures, path, wall... 

% environment automatically sends event to agents whose field of vision contains the position of the event
% -> environment predicate with instant T parameter, or does it at the current instant

environment :- 
		% current instant
		%instant(T),
		% forall explorers, for whatever they can see
		forall((explorer(Explo),cansee(Explo,Thing)),
		% send them the corresponding stimulus	
		stimulus(Explo,event(Thing,Thing))).


% interpretation of specific event position(X,Y,Obj)

%%%%%%%%%%%%%%%%%%
%%   ACTIONS    %%
%%%%%%%%%%%%%%%%%%

% beliefs about actions feasible depending on available objects
% actions need a context
% a perform method 

%%%%%%%
%% MOVE by one distance unit
%%%%%%%

% conditions: 
% be in a position X1,Y1 is necessary to move from it
% negative effect: retract the start position
% positive effect: assert the finish position
% assert knowledge about the type of terrain on the position
% assert knowledge of objects and/or agents present on that position

%:- kassert(actiondef(a,b,c,d,e,f,g)).


:- assert(actiondef(Agt,moveone(X1,Y1,X2,Y2),_Time,
	% context: move from a ground position to distance 1 ground position
	[ground(X1),ground(X2),ground(Y1),ground(Y2),distance(X1,Y1,X2,Y2,1)],
	% preconditions: agent is at start position
	[position(X1,Y1,Agt)],
	% positive effects
	[position(X2,Y2,Agt)],
	% negative effects
	[position(X1,Y1,Agt)]
)).

:- kassert(can(noa,moveone(_,_,_,_))).




% actions = move N/S/E/W by 1, attack with a weapon, pick a treasure or an object
% drop sth, recharge

% action watch in a direction: gives knowledge about what is in that direction
% up to the next wall or the end of vision field

% conditions

% condition to watch = not(know_val)
% condition to move to a place = it is a path
% effect of watching = know_val (whatever the value…) : has to read the value and put that value
% watch(Agt,PosX,PosY,Type) : type is not instantiated when performing, instantiated after

%:- kassert(bel(noa,after(noa,watch(noa,
%pompiers,done(pompiers,extinguish,_),_),firemenComing),1,0,conviction)).


% positive effects

% negative effects: after(action,not(sth))


% predicate: perform(action)
% checks condition, if fail sends fail message
% search negative effects, retracts them
% search positive effects, asserts them



% Domain actions
%:- kassert(bel(agent, after(Qqun,action(Qqun,pay_camping),bel(agent,honest(Qqun),1,_T,deduction)),1,0,conviction)).
%:- kassert(bel(agent, after(Qqun,action(Qqun,unpay_camping),bel(agent,not(honest(Qqun)),1,_T,deduction)),1,0,conviction)).
%:- kassert(bel(manager1,after(manager1,request(manager1,pompiers,done(pompiers,extinguish,_),_),firemenComing),1,0,conviction)).
%:- kassert(bel(manager1,before(manager1,request(manager1,pompiers,done(pompiers,extinguish,_),_),avoirTelephone),1,0,conviction)).





% desires = get out, get treasures, avoid enemies


% ideals 
% unideal to hit friends or teammates
% ideal to find treasures or kill enemies
% ideal to save or help teammate

% expectations : enemies are around and can kill you

% friends : 
% enemies : 

% focus: on enemies, treasures, entrance, exit…
